import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import MainContent from "@/components/MainContent";
import { useEffect, useState } from "react";
import VehicleData from "@/components/VehicleData";
import Papa from 'papaparse';
import ChartContainer from "@/components/ChartContainer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {

const [viewData, setViewData] = useState(false);
const [viewHome, setViewHome] = useState(true);
const [viewCharts, setViewCharts] = useState(false);

const [rowData, setRowData] = useState([]);
const [data, setData] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch('/Electric_Vehicle_Population_Data.csv');
      const text = await response.text();
      Papa.parse(text, {
        header: true,
        complete: (results) => {
          setRowData(results.data);
          setData(results.data)
        },
      });
    };

    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>EV Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ev.png" />
      </Head>
      <div
      >
        <div className={styles.header}>
          <img src='/vehicle.png' className={styles.image}></img>
          <h2>Electric Vehicle Analytics Dashboard</h2>
        </div>
       {viewHome && <MainContent setViewData={setViewData} setViewHome={setViewHome} setViewCharts={setViewCharts}/>}
       {viewData && <VehicleData rowData={rowData} setViewHome={setViewHome} setViewData={setViewData} setViewCharts={setViewCharts}/>}
       {viewCharts && <ChartContainer setViewData={setViewData} setViewHome={setViewHome} setViewCharts={setViewCharts} data={data}/>}
      </div>
    </>
  );
}
